spring:
  application:
    name: rouge_noir
  jmx:
    enabled: false
  datasource:
    name: source1
    driverClassName: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://xxxxxxxxxxxx:3306/rouge_noir?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: ll1992917
#    hikari
    maxLifetime: 1765000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上
    maximumPoolSize: 2 #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)


  mvc:
    dispatch-options-request: true

#
#mybatis:
#  type-aliases-package: com.sdll18.rougenoir.be.model
#  type-handlers-package: com.sdll18.rougenoir.be.model.mapper

server:
  port: 8080